### ISSUE TITLE
In Q11 Day 1 you need to create function......

### ISSUE THREAD

**Issue by ombharamadev** [kanika-bhamu/CEI_assignments#1]
![image](https://github.com/kanika-bhamu/CEI_assignments/assets/150242178/d52f968a-01ff-4631-a824-afa23181a9da)

In Q11 Day 1 you need to create function......

**Comment by kanika-bhamu** [comment]
thanks for mentioning. I have corrected the issue.

**Comment by ombharamadev** [comment]
ok done
![image](https://github.com/kanika-bhamu/CEI_assignments/assets/150242178/310bb90e-e698-45db-906d-d4517c2d1ab6)
