### ISSUE TITLE
In Q10 day 1 you need to create function 

### ISSUE THREAD

**Issue by ombharamadev** [kanika-bhamu/CEI_assignments#2]
![image](https://github.com/kanika-bhamu/CEI_assignments/assets/150242178/f1c345a3-d94c-4aca-9010-7ae23820d0d3)
In Q10 day 1 you need to create function

**Comment by kanika-bhamu** [comment]
thanks for mentioning. I have corrected the issue.

**Comment by ombharamadev** [comment]
ok done
![image](https://github.com/kanika-bhamu/CEI_assignments/assets/150242178/936f2499-61d8-417c-b7e9-1c9e2931211f)
